PLAYER = [
    [
        'resources/images/player/player_left_moving_0.png',
        'resources/images/player/player_left_moving_1.png',
        'resources/images/player/player_left_moving_2.png',
        'resources/images/player/player_left_moving_3.png'
    ],
    [
        'resources/images/player/player_right_moving_0.png',
        'resources/images/player/player_right_moving_1.png',
        'resources/images/player/player_right_moving_2.png',
        'resources/images/player/player_right_moving_3.png'
    ],
    [
        'resources/images/player/player_up_moving_0.png',
        'resources/images/player/player_up_moving_1.png',
        'resources/images/player/player_up_moving_2.png',
        'resources/images/player/player_up_moving_3.png'
    ],
    [
        'resources/images/player/player_down_moving_0.png',
        'resources/images/player/player_down_moving_1.png',
        'resources/images/Player/player_down_moving_2.png',
        'resources/images/Player/player_down_moving_3.png'
    ]
]

NEUTRAL = [
    [
        'resources/images/characters/neutral_left_0.png',
        'resources/images/characters/neutral_left_1.png',
        'resources/images/characters/neutral_left_3.png',
        'resources/images/characters/neutral_left_2.png'
    ],
    [
        'resources/images/characters/neutral_right_0.png',
        'resources/images/characters/neutral_right_1.png',
        'resources/images/characters/neutral_right_3.png',
        'resources/images/characters/neutral_right_2.png'
    ],
    [
        'resources/images/characters/neutral_up_0.png',
        'resources/images/characters/neutral_up_1.png',
        'resources/images/characters/neutral_up_2.png',
        'resources/images/characters/neutral_up_2.png'
    ],
    [
        'resources/images/characters/neutral_down_0.png',
        'resources/images/characters/neutral_down_1.png',
        'resources/images/characters/neutral_down_3.png',
        'resources/images/characters/neutral_down_2.png'
    ]
]

LIGHTING = [
    ['resources/images/shells/lighting/lightning_1.png'],
    ['resources/images/shells/lighting/lightning_2.png'],
    ['resources/images/shells/lighting/lightning_3.png'],
    ['resources/images/shells/lighting/lightning_4.png'],
    ['resources/images/shells/lighting/lightning_5.png']
]
